name: Build Core

on:
  push:
    branches:
      - develop
    paths:
      - '**.js'
      - '**.json'
      - '**.css'
      - '!dist/**'
      - '!cypress/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build Core
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update engine core
          branch: develop
          file_pattern: dist/engine/core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
